In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [3]:
img = cv2.imread("C:/Users/Jay Ajmera/Downloads/imgg.jpg")
img

array([[[126, 184, 233],
        [126, 184, 233],
        [126, 186, 232],
        ...,
        [ 63, 209, 251],
        [ 65, 213, 255],
        [ 65, 213, 255]],

       [[126, 184, 233],
        [125, 184, 233],
        [126, 186, 232],
        ...,
        [ 61, 209, 251],
        [ 64, 212, 254],
        [ 63, 213, 254]],

       [[126, 185, 234],
        [124, 186, 234],
        [124, 186, 232],
        ...,
        [ 59, 208, 252],
        [ 61, 210, 254],
        [ 59, 210, 254]],

       ...,

       [[ 99, 225, 253],
        [ 99, 225, 253],
        [100, 224, 254],
        ...,
        [  0,  99,  47],
        [  0,  95,  45],
        [  2,  94,  45]],

       [[ 99, 225, 253],
        [ 99, 225, 253],
        [ 99, 225, 253],
        ...,
        [  3, 101,  49],
        [  0,  95,  45],
        [  2,  94,  45]],

       [[ 99, 225, 253],
        [ 99, 225, 253],
        [ 99, 225, 253],
        ...,
        [  6, 104,  52],
        [  0,  95,  45],
        [  2,  94,  45]]

In [12]:
#full pic blur
id_kern = np.array([[0,0,0],[0,1,0],[0,0,0]])
id_kern

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])

In [13]:
blurring_kern3 = np.ones((3,3),dtype = np.float32)/9.0
blurring_kern11 = np.ones((11,11),dtype = np.float32)/121.0
blurring_kern11

array([[0.00826446, 0.00826446, 0.00826446, 0.00826446, 0.00826446,
        0.00826446, 0.00826446, 0.00826446, 0.00826446, 0.00826446,
        0.00826446],
       [0.00826446, 0.00826446, 0.00826446, 0.00826446, 0.00826446,
        0.00826446, 0.00826446, 0.00826446, 0.00826446, 0.00826446,
        0.00826446],
       [0.00826446, 0.00826446, 0.00826446, 0.00826446, 0.00826446,
        0.00826446, 0.00826446, 0.00826446, 0.00826446, 0.00826446,
        0.00826446],
       [0.00826446, 0.00826446, 0.00826446, 0.00826446, 0.00826446,
        0.00826446, 0.00826446, 0.00826446, 0.00826446, 0.00826446,
        0.00826446],
       [0.00826446, 0.00826446, 0.00826446, 0.00826446, 0.00826446,
        0.00826446, 0.00826446, 0.00826446, 0.00826446, 0.00826446,
        0.00826446],
       [0.00826446, 0.00826446, 0.00826446, 0.00826446, 0.00826446,
        0.00826446, 0.00826446, 0.00826446, 0.00826446, 0.00826446,
        0.00826446],
       [0.00826446, 0.00826446, 0.00826446, 0.00826446, 0.

In [14]:

out1 = cv2.filter2D(img,-1,id_kern)
out2 = cv2.filter2D(img,-1,blurring_kern3)
out3 = cv2.filter2D(img,-1,blurring_kern11)
out1

array([[[126, 184, 233],
        [126, 184, 233],
        [126, 186, 232],
        ...,
        [ 63, 209, 251],
        [ 65, 213, 255],
        [ 65, 213, 255]],

       [[126, 184, 233],
        [125, 184, 233],
        [126, 186, 232],
        ...,
        [ 61, 209, 251],
        [ 64, 212, 254],
        [ 63, 213, 254]],

       [[126, 185, 234],
        [124, 186, 234],
        [124, 186, 232],
        ...,
        [ 59, 208, 252],
        [ 61, 210, 254],
        [ 59, 210, 254]],

       ...,

       [[ 99, 225, 253],
        [ 99, 225, 253],
        [100, 224, 254],
        ...,
        [  0,  99,  47],
        [  0,  95,  45],
        [  2,  94,  45]],

       [[ 99, 225, 253],
        [ 99, 225, 253],
        [ 99, 225, 253],
        ...,
        [  3, 101,  49],
        [  0,  95,  45],
        [  2,  94,  45]],

       [[ 99, 225, 253],
        [ 99, 225, 253],
        [ 99, 225, 253],
        ...,
        [  6, 104,  52],
        [  0,  95,  45],
        [  2,  94,  45]]

In [ ]:
cv2.imshow('same',out1)
cv2.imshow('3',out2)
cv2.imshow('11',out3)
cv2.waitKey(0)

In [ ]:
#motion blur

In [4]:
size = 15
kernel = np.zeros((size,size))
kernel[:,7]= np.ones(size)
#for horizontal motion blurring make the middle column = 1
kernel = kernel/size
output= cv2.filter2D(img, -1, kernel)
kernel


array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.06666667, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.06666667, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.06666667, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.06666667, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.06666667, 0.        , 0.        ,
        0.        , 0.        , 0.        , 

In [ ]:
cv2.imshow( 'motion blur' , output)
cv2.imshow('og', img)
cv2.waitKey(0)

In [4]:
#sharpening
#subtract blurred image from og image
#Gauusian kernel for sharpening
gaussian_blur = cv2.GaussianBlur(img,(7,7), 2)
#Sharpening using addweighted( )
sharpened1 = cv2.addWeighted(img, 1.5,gaussian_blur,-0.5,0)
sharpened2 = cv2.addWeighted(img, 4.5,gaussian_blur,-3.5,0)
sharpened3 = cv2.addWeighted(img, 7.5,gaussian_blur,-6.5,0)
#

In [5]:
#Showing the sharpened Images
cv2.imshow('Sharpened3' , sharpened3)
cv2.imshow('Sharpened2' , sharpened2)
cv2.imshow('Sharpened1' , sharpened1)
cv2.waitKey(0)

-1

In [6]:


# orginal image
img = cv2.imread("C:/Users/Jay Ajmera/Downloads/imgg.jpg",0)
img = img/255

cv2.imshow('original image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# blank image
x,y = img.shape
g = np.zeros((x,y), dtype=np.float32)

# salt and pepper amount
pepper = 0.1
salt = 0.95

# create salt and peper noise image    
for i in range(x):
    for j in range(y):
        rdn = np.random.random()
        if rdn < pepper:
            g[i][j] = 0
        elif rdn > salt:
            g[i][j] = 1
        else:
            g[i][j] = img[i][j]

cv2.imshow('image with noise', g)
cv2.waitKey(0)

-1

In [7]:
img

array([[0.75294118, 0.75294118, 0.75686275, ..., 0.80392157, 0.81960784,
        0.81960784],
       [0.75294118, 0.75294118, 0.75686275, ..., 0.80392157, 0.81568627,
        0.81568627],
       [0.75686275, 0.75686275, 0.75686275, ..., 0.8       , 0.80784314,
        0.80784314],
       ...,
       [0.85882353, 0.85882353, 0.85882353, ..., 0.28235294, 0.27058824,
        0.27058824],
       [0.85882353, 0.85882353, 0.85882353, ..., 0.29019608, 0.27058824,
        0.27058824],
       [0.85882353, 0.85882353, 0.85882353, ..., 0.30196078, 0.27058824,
        0.27058824]])

In [13]:

from skimage import img_as_ubyte

## original image
img = cv2.imread("C:/Users/Jay Ajmera/Downloads/rode_wali.jpg")
img = img/img.max() # normalize the pixel value (0~1)

## noise image
# Gaussian Noise
# =============================================================================
# x, y = img.shape
# mean = 0
# var = 0.01
# sigma = np.sqrt(var)
# n = np.random.normal(loc=mean, 
#                      scale=sigma, 
#                      size=(x,y))
# img_noise = img + n
# =============================================================================

# Salt and Pepper Noise

## denoise image
# mean filter (average)
m = 5
n = 5
denoise_mean = cv2.blur(img, (m,n))

# median filter
img_noise_median = np.clip(img, -1, 1) #pixel value range
img_noise_median = img_as_ubyte(img_noise_median) #convert to uint8
denoise_median = cv2.medianBlur(img_noise_median, 5)

# preview the images
cv2.imshow('Original Image', img)
cv2.imshow('Image + Noise', img)
cv2.imshow('Denoise Mean', denoise_mean)

cv2.waitKey(0)

-1

In [14]:
cv2.imshow('Denoise Median', denoise_median)
cv2.waitKey(0)

-1